updates:
  - directory: /
    groups:
      aws-s3:
        patterns:
          - '@aws-sdk/client-s3'
          - '@aws-sdk/s3-request-presigner'
      nest-core:
        patterns:
          - '@nestjs/core'
          - '@nestjs/common'
          - '@nestjs/platform-express'
          - '@nestjs/testing'
    ignore:
      - dependency-name: serialize-error
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
